### ISSUE TITLE
Minimum Kickstart required?

### ISSUE THREAD

**Issue by RolandJuno** [C4ptFuture/cdtv-os235patch#4]
I'm hoping to use this with Kickstart 1.3 but can't find the minimum required Kickstart version in the docs.

**Comment by C4ptFuture** [comment]
Hi, it is mentioned in the FAQ document here: https://github.com/C4ptFuture/cdtv-os235patch/blob/master/README-faq.md#what-kickstart-rom-versions-are-compatible-with-cdtv-os-235
