### ISSUE TITLE
Feature request - Exit CDTV screen after timeout

### ISSUE THREAD

**Issue by LIV2** [C4ptFuture/cdtv-os235patch#6]
First off, great work on this! It's really great that the CDTV can now work with 32-bit fast ram etc and impressive work you've done.

The timeout function before booting from HDD is great too, it's just unfortunate that autoconfig IDE devices can't take advantage of this situation - I'm guessing CDStrap doesn't initialise expansion ROMs or something.

Would it be possible to have a configurable timeout so that the CDTV will exit to the normal strap just like when you hit ESC?

**Comment by C4ptFuture** [comment]
Thx for the suggestion! I've been considering adding autoboot support in 2.36 for well known devices like e.g. oktagon.device based boards, simply by having cdstrap query expansion.library for the presence of well known Autoconfig Manufacturer ID and Prod ID combinations. If a known board is found, then cdstrap should auto exit (observing the HDD autoboot delay) to make the system initialization fall through to the normal strap module in the Kickstart ROM, which should then take care of initializing the Autoconfig ROM based driver and autoboot as normal. Would this type of solution work for your use case as well?
 
As for the actual list of Autoconfig IDs. I am considering storing well known IDs in ROM, so those devices will work out-of-the-box. But I would also like to support additional Autoconfig IDs that can be stored in bookmark memory by the end user, to also allow more exotic hardware to autoboot on CDTV.

**Comment by LIV2** [comment]
That sounds like a really neat solution to this problem :) 

If you go down that route could you please add [CIDER](https://github.com/LIV2/CIDER) to your builtin ID list?
Manufacturer: 0x144A
Prod: 0x05

**Comment by C4ptFuture** [comment]
Sure. Consider it added to the list 👍😃

**Comment by LIV2** [comment]
Awesome thanks!
